version: '3'
services:
  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
  app:
    build: .
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
    ports:
      - 8501:8501
    depends_on:
      - ollama